services:
  job_dispatcher:
    build: ./remote_clp_service/job_dispatcher
    container_name: job_dispatcher
    entrypoint: ["/app/wait-for-it.sh", "rabbitmq:5672", "-t", "600", "--", "/app/job_dispatcher"]
    depends_on:
      - rabbitmq
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_JOBS_QUEUE=remote-clp-jobs
      - RABBITMQ_STATUS_QUEUE=remote-clp-status
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  worker:
    build: ./remote_clp_service/worker
    entrypoint: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "600", "--", "python", "app.py"]
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_JOBS_QUEUE=remote-clp-jobs
      - RABBITMQ_STATUS_QUEUE=remote-clp-status

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_log:
